name: Containers
on: push
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:lts-alpine3.14
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
