name: Secrets
on: push
env:
  SECRET_ENV: ${{secrets.SECRET_ENV}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # Github token to use Github API
jobs:
  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: Log Secret
        run: |
          echo "Secret: ${SECRET_ENV}"
