name: Secrets
on: push
env:
  SECRET_ENV: ${{secrets.SECRET_ENV}}

jobs:
  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: Log Secret
        run: |
          echo "Secret: ${SECRET_ENV}"
